- id: gradle-checkstyle-main
  name: gradle checkstyleMain
  description: Run gradle checkstyle for main
  entry: pre_commit_hooks/gradle-checkstyle-main.sh
  language: script
- id: gradle-checkstyle-test
  name: gradle checkstyleTest
  description: Run gradle checkstyle for test
  entry: pre_commit_hooks/gradle-checkstyle-test.sh
  language: script